### ISSUE TITLE
Cannot find module "discord.js"

### ISSUE THREAD

**Issue by fox365** [thehink/discord-psn-status#1]
I filled in the info on config.json but when I do a go to run index.js it throws an error.

```
module.js:549
   throw err;
   ^

Error: Cannot find module 'discord.js'
   at Function.Module._resolveFilename (module.js:547:15)
   at Function.Module._load (module.js:474:25)
   at Module.require (module.js:596:17)
   at require (internal/module.js:11:18)
   at Object.<anonymous> (/home/jeff/apps/discord-psn-status/index.js:1:79)
   at Module._compile (module.js:652:30)
   at Object.Module._extensions..js (module.js:663:10)
   at Module.load (module.js:565:32)
   at tryModuleLoad (module.js:505:12)
   at Function.Module._load (module.js:497:3)

```
Also, I assume this requires me not to use 2FA on PSN?

**Comment by vladtvoeit** [comment]
npm install discord.js
